steps:
    - id: "Build frontend"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/pushpong_frontend", "."]
    
    - id: "Build backend"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/pushpong_backend", "."]

    - id: "Push up built frontend image"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/push-pong/pushpong_frontend"]
    
    - id: "Push up built backend image"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/push-pong/pushpong_backend"]
