steps:
    # Build frontend
    - name: "gcr.io/push-pong/pushpong_frontend"
      args: ["build", "-t", "gcr.io/push-pong/pushpong_frontend", "."]
    
    # Build backend
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/push-pong/pushpong_backend", "."]

    # Push up built frontend image
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/push-pong/pushpong_frontend"]
    
    # Push up built backend image
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/push-pong/pushpong_backend"]
