version: '3'

services:
    frontend:
        image: pushpong_frontend:latest
        build:
            context: ./frontend
            args:
                app_env: dev
                backend_host: localhost
                backend_port: 5000
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - frontend-deps:/frontend/node_modules

    backend:
        image: pushpong_backend:latest
        build:
            context: ./backend
            args:
                app_env: dev
        command: npm start
        ports:
            - "5000:5000"
        volumes:
            - ./backend/:/backend
            - backend-deps:/backend/node_modules

volumes:
    frontend-deps:
    backend-deps:
