version: '3'

services:
    backend:
        image: pushpong_backend
        build:
            context: ./backend
        command: sh ./scripts/docker-start-dev.sh
        ports:
            - 3000:3000
        stdin_open: true
        volumes:
            - ./backend/:/backend
            - backend-deps:/backend/node_modules

    frontend:
        image: pushpong_frontend
        depends_on:
            - backend
        build:
            context: ./frontend
        environment:
            - REACT_APP_BACKEND_PROTOCOL=http
            - REACT_APP_BACKEND_HOST=localhost
            - REACT_APP_BACKEND_PORT=3000
        command: sh ./scripts/docker-start-dev.sh
        ports:
            - 3001:3001
        stdin_open: true
        volumes:
            - ./frontend:/frontend
            - frontend-deps:/frontend/node_modules

volumes:
    backend-deps:
    frontend-deps:
